### ISSUE TITLE
Crash after the tenth scan.

### ISSUE THREAD

**Issue by WayneBooth** [clearscene/opendias#23]
- Occaisonal total crash of the openDIAS process on the server - happened twice now, I've upped the log verbosity to try and catch it next time. Both previous occurances were immediately after a scan.

Further update on this - it's happening at a rate of once per 10 scans, and the error popup is:

 [a002] Error while talking to the server: error

There's nothing logged to the OpenDias logs, not even at log level 4. My only workaround is to keep a shell open on the openDias server to restart the process while scanning, but that means I can't leave my wife to do any scanning, as it's bound to choose that time to fall over. Pretty nasty.

**Comment by GregSutcliffe** [comment]
From your notes in the forum, I think a crash in the phash process fits the evidence. I tried to watch closely as it happened one time, and thats when openDIAS seems to die. The evidence is that when I restart it and log back in, the document has been correctly saved (albeit with Untitled Document, no tags, etc) - so the image has been captured and stored.

Shout if there's any more testing I can do.

**Comment by WayneBooth** [comment]
I have been unable to replicate this, either via regression tests or attempting to replicate on a full system.
Since this issue has been reported, I have re-written the mechanism around how the sane dispatcher creates a new processes. So for now, I'm going to mark this as closed.
However I understand that this is a real problem. If (after upgrading to the latest version) you see this again, please can you include the log with a verbosity setting of DEBUGM or above. Also, if you can start with "ulimit -c unlimited" and send the generated dump file for analysis.

**Comment by GregSutcliffe** [comment]
Will do. Looking forward to the new build - feel free to fire test debs in my general direction, by the way :)

**Comment by WayneBooth** [comment]
Actually, it occurs to me - Are you running 0.9,3b on Debian Squeeze? using a pre-build deb package?
If so, Squeeze libraries are too far behind to support OCR and pHash. This may be the source of the crashes.
I'm going to be building a Wheezy machine to ensure things work OK on that. If so, I'll generate a deb specifically for it.

**Comment by GregSutcliffe** [comment]
Sadly no, it's an ubuntu machine, Ubuntu 12.04.2 LTS to be precise.
