### ISSUE TITLE
autocomplete drop downs can be in odd locations

### ISSUE THREAD

**Issue by WayneBooth** [clearscene/opendias#26]
- Popups appear in odd places - particularly when offering completions for tag names, the list of completions seems to appear in random places on the page. Screenshot available on request

**Comment by WayneBooth** [comment]
I'm putting this down to an old version of JQuery which is due for a refresh in the next version.
What version browser are you using?

**Comment by GregSutcliffe** [comment]
Chromium    26.0.1410.63 (Developer Build 192696) 

I'll keep an eye out for it happening again :)
