### ISSUE TITLE
[bug][critical] Attempting to edit OCR'ed text crashes OpenDias

### ISSUE THREAD

**Issue by GregSutcliffe** [clearscene/opendias#44]
Steps to reproduce:
- Log in
- Go to Document List
- Edit a Document
- Change the OCR'd text in the textarea
- Click away from the OCR text to save it

Result: Popup containing `[s001] Error while talking to the server: Error` and OpenDias has crashed. Nothing useful in the logs:

```
20130514222942:F5FA2700:DBG:web_handler.c:397 Language setting (from header) is: en
20130514222942:F5FA2700:DBG:web_handler.c:458 Client provided session cookie: 62c84af6-c2d8-4ad6-a8cc-e578077830c3
20130514222942:F5FA2700:DBG:web_handler.c:471 Using session: 62c84af6-c2d8-4ad6-a8cc-e578077830c3
20130514222942:F5FA2700:DBG:web_handler.c:473 Session contains: 
      username : greg
      realname : Greg
      role : 2
```

What's way to get more detailed logging?

**Comment by WayneBooth** [comment]
This is fixed in commit [f1f79376ad] which will be in the next version.
